[[unit]]
name = "DinoFigher"
pub_name = "Dino Fighter"
max_hp = 2
move_range = 1
attack_range = 1
damage = 2
cost = 2
sprite_idx = 0
faction = "Dinosaur"

[[unit]]
name = "DinoRanged"
pub_name = "Dino Ranged"
max_hp = 1
move_range = 1
attack_range = 2
damage = 2
cost = 2
sprite_idx = 1
faction = "Dinosaur"

[[unit]]
name = "DinoScout"
pub_name = "Dino Scout"
max_hp = 1
move_range = 2
attack_range = 1
damage = 1
cost = 3
sprite_idx = 2
faction = "Dinosaur"

[[unit]]
name = "LavaGolem"
pub_name = "Lava Golem"
max_hp = 4
move_range = 1
attack_range = 1
damage = 2
cost = 2
sprite_idx = 3
faction = "Volcano"

[[unit]]
name = "Lava"
pub_name = "Lava"
max_hp = 0
move_range = 0
attack_range = 0
damage = 1
cost = 2
sprite_idx = 4
faction = "Volcano"

[[unit]]
name = "VolcanoRocks"
pub_name = "Volcano Rocks"
max_hp = 0
move_range = 0
attack_range = 3
damage = 1
cost = 4
sprite_idx = 5
faction = "Volcano"
